# @CTRLPlusN/Modules/routing.yml

# Commenter pour désactiver un routage d'une modulerairie
ctrln_routes_module.review:
    resource: "@CTRLPlusN/Modules/ReviewModule/config/routing.yml"
    prefix:   /
    
ctrln_routes_module.link:
    resource: "@CTRLPlusN/Modules/LinkModule/config/routing.yml"
    prefix:   /