# @CTRLPlusN/Modules/routing.yml

# Commenter pour désactiver un routage d'une modulerairie
ctrln_routes_module.review:
    resource: "@CTRLPlusN/Modules/ReviewModule/config/routing.yml"
    prefix:   /
    
ctrln_routes_module.picture:
    resource: "@CTRLPlusN/Modules/PictureModule/config/routing.yml"
    prefix:   /
    
ctrln_routes_module.link:
    resource: "@CTRLPlusN/Modules/LinkModule/config/routing.yml"
    prefix:   /
    
ctrln_routes_module.guestbook:
    resource: "@CTRLPlusN/Modules/GuestbookModule/config/routing.yml"
    prefix:   /
    
ctrln_routes_module.slideshow:
    resource: "@CTRLPlusN/Modules/SlideshowModule/config/routing.yml"
    prefix:   /
    
ctrln_routes_module.subscriber:
    resource: "@CTRLPlusN/Modules/SubscriberModule/config/routing.yml"
    prefix:   /
    
ctrln_routes_module.staticpage:
    resource: "@CTRLPlusN/Modules/StaticPageModule/config/routing.yml"
    prefix:   /