# @CTRLPlusN\Modules\ReviewManagement\config\config.yml
services:
    module.review_management:
        class: CTRLPlusN\Modules\ReviewManagement\ReviewManagement
        arguments : [ "@service_container", "@doctrine.orm.entity_manager" ]
    review.type.post:
        class: CTRLPlusN\Modules\ReviewManagement\Form\PostType
        arguments: [ "@doctrine.orm.entity_manager" ]
        tags:
            - { name: form.type }
   # Post Researcher
    review.type.research:
        class: CTRLPlusN\Modules\ReviewManagement\Form\ResearchType
        arguments: [ "@router" ]
        tags:
            - { name: form.type }
    review.researcher.ext:
        class: CTRLPlusN\Modules\ReviewManagement\Twig\Extension\ResearcherExtension
        arguments: [ "@doctrine.orm.entity_manager", "@service_container" ]
        tags:
            - { name: twig.extension }
    review.researcher.helper:
        class : CTRLPlusN\Modules\ReviewManagement\Twig\Helper\ResearcherHelper
        arguments : [ "@templating" ]
        tags :
         - { name : 'templating.helper', alias : 'review_researcher_helper' }
         
   # Widget : Breadcrumb
    review.widget.breadcrumb:
        class : CTRLPlusN\Modules\ReviewManagement\Widget\Breadcrumb\BreadcrumbWidget

    # Widget : ReviewBlock
    review.widget.review_block:
        class : CTRLPlusN\Modules\ReviewManagement\Widget\ReviewBlock\ReviewBlockWidget
        arguments: [ "@doctrine.orm.entity_manager", "@service_container" ]
    review.widget.review_block.ext:
        class : CTRLPlusN\Modules\ReviewManagement\Widget\ReviewBlock\TwigExtension\ReviewBlockExtension
        arguments: [ "@service_container" ]
        tags:
            - { name: twig.extension }
    review.widget.review_block.helper:
        class : CTRLPlusN\Modules\ReviewManagement\Widget\ReviewBlock\Helper\ReviewBlockHelper
        arguments : [ "@templating" ]
        tags :
         - { name : 'templating.helper', alias : 'reviewblock_helper' }
         
imports:

parameters:
    # Configuration de l'admin menu
    menu.admin.review_management:
        - { icon: newspaper, name: Article, route: admin_post_index, params: {} }
        - { icon: bookmark, name: Catégorie, route: admin_category_index, params: {} }

twig:
    paths:
        "%kernel.root_dir%/../src/CTRLPlusN/Modules/ReviewManagement/Views": review

doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    Review:
                        type: annotation
                        dir: '%kernel.root_dir%/../src/CTRLPlusN/Modules/ReviewManagement/Entity'
                        prefix: CTRLPlusN\Modules\ReviewManagement\Entity
                        alias: Review
                        is_bundle: false