# @CTRLPlusN\Modules\PictureModule\config\config.yml
services:
    module.picture_module:
        class: CTRLPlusN\Modules\PictureModule\PictureModule
        arguments : [ "@service_container" ]

imports:

parameters:
    menu.admin.picture_module:
        - { icon: folder-open-o, name: Albums, route: admin_album_index, params: {} }
        - { icon: picture-o, name: Photos, route: admin_image_index, params: {} }
        
twig:
    paths:
        "%kernel.root_dir%/../src/CTRLPlusN/Modules/PictureModule/Views": picture
        
doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    Picture:
                        type: annotation
                        dir: '%kernel.root_dir%/../src/CTRLPlusN/Modules/PictureModule/Entity'
                        prefix: CTRLPlusN\Modules\PictureModule\Entity
                        alias: Picture
                        is_bundle: false